/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportcheck;

import java.awt.GraphicsConfiguration;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohd Samir
 */
public class Baggage_Details1 extends javax.swing.JFrame {
    public String a;
    int b,c,d,e;
    public static int array[];
    public static String array1[];
    public Baggage_Details1(int [] array) {
        Report r =  new Report(array);
        r.setVisible(true);
                
    }

    
    
    /**
     * Creates new form Baggage_Details
     */
    public Baggage_Details1() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        show_Validation_Message = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SubmitButtonBag = new javax.swing.JButton();
        homepageButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PaidExtraInt = new javax.swing.JTextField();
        ExtraBagInt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NumberOfbagInt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        baggageWeightInt = new javax.swing.JTextField();
        BaggageDimentionInt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 780));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 126, 28));
        jLabel1.setText("Customer Baggage Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 40, 291, 29);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(335, 188, 0, 0);

        show_Validation_Message.setForeground(java.awt.Color.red);
        jPanel1.add(show_Validation_Message);
        show_Validation_Message.setBounds(620, 60, 260, 0);

        jPanel2.setBackground(new java.awt.Color(165, 249, 165));
        jPanel2.setLayout(null);

        SubmitButtonBag.setBackground(new java.awt.Color(102, 255, 0));
        SubmitButtonBag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitButtonBag.setText("Insert");
        SubmitButtonBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonBagActionPerformed(evt);
            }
        });
        jPanel2.add(SubmitButtonBag);
        SubmitButtonBag.setBounds(26, 418, 120, 40);

        homepageButton.setBackground(new java.awt.Color(255, 204, 102));
        homepageButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        homepageButton.setText("Back");
        homepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageButtonActionPerformed(evt);
            }
        });
        jPanel2.add(homepageButton);
        homepageButton.setBounds(214, 418, 110, 40);

        logoutButton.setBackground(new java.awt.Color(255, 102, 102));
        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setText("LogOut");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton);
        logoutButton.setBounds(384, 418, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Excess Baggage Fee :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(16, 330, 150, 44);

        PaidExtraInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PaidExtraIntKeyPressed(evt);
            }
        });
        jPanel2.add(PaidExtraInt);
        PaidExtraInt.setBounds(190, 330, 320, 44);

        ExtraBagInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraBagIntActionPerformed(evt);
            }
        });
        ExtraBagInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ExtraBagIntKeyPressed(evt);
            }
        });
        jPanel2.add(ExtraBagInt);
        ExtraBagInt.setBounds(190, 270, 320, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter excess Baggage :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 270, 190, 44);

        NumberOfbagInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfbagIntActionPerformed(evt);
            }
        });
        jPanel2.add(NumberOfbagInt);
        NumberOfbagInt.setBounds(190, 210, 320, 43);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Number of  Baggage :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 210, 200, 40);

        baggageWeightInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                baggageWeightIntKeyPressed(evt);
            }
        });
        jPanel2.add(baggageWeightInt);
        baggageWeightInt.setBounds(190, 150, 320, 43);

        BaggageDimentionInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaggageDimentionIntActionPerformed(evt);
            }
        });
        BaggageDimentionInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BaggageDimentionIntKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BaggageDimentionIntKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BaggageDimentionIntKeyTyped(evt);
            }
        });
        jPanel2.add(BaggageDimentionInt);
        BaggageDimentionInt.setBounds(190, 90, 320, 39);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter Baggage Weight :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 150, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Enter Baggage Volume :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 90, 220, 39);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 90, 560, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaggageDimentionIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaggageDimentionIntActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BaggageDimentionIntActionPerformed

    private void ExtraBagIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraBagIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraBagIntActionPerformed
class Pojo {
    private int a;
    private int b ;
    private int c ;
    private int d ;
    private int e;

        public int getA() {
            return a;
        }

        public void setA(int a) {
            this.a = a;
        }

        public int getB() {
            return b;
        }

        public void setB(int b) {
            this.b = b;
        }

        public int getC() {
            return c;
        }

        public void setC(int c) {
            this.c = c;
        }

        public int getD() {
            return d;
        }

        public void setD(int d) {
            this.d = d;
        }

        public int getE() {
            return e;
        }

        public void setE(int e) {
            this.e = e;
        }
    
    
}
    private void SubmitButtonBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonBagActionPerformed
       Pojo p = new Pojo();
       
       a = BaggageDimentionInt.getText().toString();
       b = Integer.parseInt(baggageWeightInt.getText());
       c=Integer.parseInt(NumberOfbagInt.getText());
         d = Integer.parseInt(ExtraBagInt.getText());
         e=Integer.parseInt(PaidExtraInt.getText());
           //a = BaggageDimentionInt.getText().toString();
       
       if(BaggageDimentionInt.getText().trim().isEmpty() && baggageWeightInt.getText().trim().isEmpty() && 
               NumberOfbagInt.getText().trim().isEmpty() && ExtraBagInt.getText().trim().isEmpty() && PaidExtraInt.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(rootPane, "Field(s) are Empty.");
       }
       
       
      
      
       array= new int[10];
       array1= new String[10];
       try{
           
         for(int i=0; i<=4; i++){
          array1[0]=a;
        //  sumA+=a;
          array[0]=b;
         
        //  try{
         array[1]=c;
         array[2]=d;
         array[3]=e;
//         if(c>1){
//             JOptionPane.showMessageDialog(null, Create_Own_Exception.validateBag(2));
//             this.dispose();
//         }
//         JOptionPane.showMessageDialog(null, Create_Own_Exception.validateBag(1));
//         this.dispose();
         
//          }catch(Exception es) {
//              System.out.println("");
//          }
       
          
         }
         
          JOptionPane.showMessageDialog(rootPane, "Inserted Data..");
         
       }catch(Exception e4){
           JOptionPane.showMessageDialog(rootPane, "Invalid Insertion "+e4);
       }
       
//           Report r = new Report();
//           r.setVisible(true);
//           this.dispose();
//       for(int i= 0 ;i<=4;i++){
//        System.out.println(array[i]);
//       }
    }//GEN-LAST:event_SubmitButtonBagActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        AirportCheckInSystem a=new AirportCheckInSystem();
        this.dispose();
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void homepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageButtonActionPerformed
        
         HomePage h = new HomePage();
       h.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homepageButtonActionPerformed

    private void NumberOfbagIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfbagIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfbagIntActionPerformed

    private void BaggageDimentionIntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BaggageDimentionIntKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BaggageDimentionIntKeyTyped

    private void BaggageDimentionIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BaggageDimentionIntKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_BaggageDimentionIntKeyPressed

    private void baggageWeightIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baggageWeightIntKeyPressed
        // TODO add your handling code here:
     //    try{
//       
//            try{
//            b = Integer.parseInt(baggageWeightInt.getText());
//               if(b <= 20){
//           JOptionPane.showMessageDialog(rootPane, "No any excess fee.");
//       }else{
//           JOptionPane.showMessageDialog(rootPane, "Excess fee paid");
//       }
//            }
//            catch(NumberFormatException e3){
//              show_Validation_Message.setText("Invalid Input");  
//            }
//            
            
           
//        }catch(NumberFormatException e2){
//            show_Validation_Message.setText("Invalid Number");
//        }
//         
         
        
      
      
       
       
       
    
       
       
       
       
      
    }//GEN-LAST:event_baggageWeightIntKeyPressed

    private void ExtraBagIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExtraBagIntKeyPressed
//        try{
//           d = Integer.parseInt(ExtraBagInt.getText());
//          if(d>=1){
//           JOptionPane.showMessageDialog(rootPane, "Enter Number for extra bag.");
//       }
//          else{
//              JOptionPane.showMessageDialog(rootPane, "No extra fee.");
//          }
//            }catch(NumberFormatException e6){
//              show_Validation_Message.setText("Invalid Input");  
//            }
    }//GEN-LAST:event_ExtraBagIntKeyPressed

    private void PaidExtraIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaidExtraIntKeyPressed
//         try{
//             e = Integer.parseInt(PaidExtraInt.getText());
//           
//       if(e<=0){
//           JOptionPane.showMessageDialog(rootPane, "No Extra Bag then Enter zero (0) .");
//       }else{
//           JOptionPane.showMessageDialog(rootPane, "Enetr excess fee.. ");
//       }
//            }catch(NumberFormatException e7){
//              show_Validation_Message.setText("Invalid Input");  
//            }
    }//GEN-LAST:event_PaidExtraIntKeyPressed

    private void BaggageDimentionIntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BaggageDimentionIntKeyReleased
        // TODO add your handling code here:
           try{
          a = BaggageDimentionInt.getText().toString();
        
        ValidationOfVolumeUsingPattern v = new ValidationOfVolumeUsingPattern();
       v.validate(a);
       String s = "TRUE";
       if(a != null){
           JOptionPane.showMessageDialog(rootPane, "Enter Dimension / volume like this ->  20x30x40  ");
       }else{
         JOptionPane.showMessageDialog(rootPane, "  ");
       }
           
            } catch(NumberFormatException e3){
                JOptionPane.showMessageDialog(rootPane,  " ");
            }
    }//GEN-LAST:event_BaggageDimentionIntKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baggage_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baggage_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baggage_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baggage_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baggage_Details1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BaggageDimentionInt;
    private javax.swing.JTextField ExtraBagInt;
    private javax.swing.JTextField NumberOfbagInt;
    private javax.swing.JTextField PaidExtraInt;
    private javax.swing.JButton SubmitButtonBag;
    private javax.swing.JTextField baggageWeightInt;
    private javax.swing.JButton homepageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel show_Validation_Message;
    // End of variables declaration//GEN-END:variables
}
