/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportcheck;



import java.io.BufferedReader;
import java.io.File;

import java.io.FileReader;
import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mohd Samir
 */



 public class Flight_Details1 extends javax.swing.JFrame {
   
public static int countCheckIn=1;
    /**
     * Creates new form Flight_Details
     */
    public Flight_Details1() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        homepageButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 780));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Flight Booking List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 20, 192, 29);

        show.setBackground(new java.awt.Color(102, 255, 102));
        show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        show.setText("Show List");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showKeyPressed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(360, 100, 140, 50);

        homepageButton.setBackground(new java.awt.Color(255, 204, 102));
        homepageButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        homepageButton.setText("Back");
        homepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homepageButton);
        homepageButton.setBounds(580, 100, 140, 50);

        LogoutButton.setBackground(new java.awt.Color(255, 102, 102));
        LogoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutButton);
        LogoutButton.setBounds(800, 100, 140, 50);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 160, 580, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
       

        String filePath = "C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\FlightDetails.csv";
             File file = new File(filePath);
        
        try {
             
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split("\t\t\t");
           DefaultTableModel model = (DefaultTableModel)Table1.getModel();
           model.setColumnIdentifiers(columnsName);
           Object[] tableLines = br.lines().toArray();
            for(int i = 0; i<tableLines.length; i++){
                countCheckIn++;
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
               model.addRow(dataRow);
 
           }
       } catch (IOException ex) {
           Logger.getLogger(Flight_Details1.class.getName()).log(Level.SEVERE, null, ex);
      }                  
  
    }//GEN-LAST:event_showActionPerformed

    private void homepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageButtonActionPerformed
         HomePage h = new HomePage();
       h.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_homepageButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        
        AirportCheckInSystem a=new AirportCheckInSystem();
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
    
       
                
        
    }//GEN-LAST:event_showMouseClicked

    private void showKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showKeyPressed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_showKeyPressed

    /**
     * @param args the command line arguments
     */
 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight_Details1().setVisible(true);
               
            }
        });

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTable Table1;
    private javax.swing.JButton homepageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}