/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportcheck;

import java.io.*;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.io.FileWriter;
//import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohd Samir
 */
public class HomePage2 extends javax.swing.JFrame {

    /**
     * Creates new form HomePage2
     */
    public HomePage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        CheckBtnDesk = new javax.swing.JButton();
        watingBtn = new javax.swing.JButton();
        statusBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("homePage2");

        jPanel1.setToolTipText("Stage2");
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 780));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 61, 74));
        jLabel1.setText("Stage2");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 40, 110, 44);

        jPanel2.setBackground(new java.awt.Color(212, 253, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 255)));
        jPanel2.setLayout(null);

        exitBtn.setBackground(new java.awt.Color(204, 255, 204));
        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitBtn.setText("LogFile");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn);
        exitBtn.setBounds(80, 300, 460, 40);

        LogoutBtn.setBackground(new java.awt.Color(253, 220, 221));
        LogoutBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LogoutBtn);
        LogoutBtn.setBounds(80, 380, 100, 40);

        ExitBtn.setBackground(new java.awt.Color(255, 153, 102));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitBtn.setText("Home");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ExitBtn);
        ExitBtn.setBounds(430, 380, 110, 40);

        CheckBtnDesk.setBackground(new java.awt.Color(255, 204, 204));
        CheckBtnDesk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CheckBtnDesk.setText("Check In Desk");
        CheckBtnDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBtnDeskActionPerformed(evt);
            }
        });
        jPanel2.add(CheckBtnDesk);
        CheckBtnDesk.setBounds(80, 140, 460, 40);

        watingBtn.setBackground(new java.awt.Color(255, 204, 204));
        watingBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        watingBtn.setText("Waiting Queue");
        watingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watingBtnActionPerformed(evt);
            }
        });
        jPanel2.add(watingBtn);
        watingBtn.setBounds(80, 60, 460, 40);

        statusBtn.setBackground(new java.awt.Color(255, 204, 204));
        statusBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusBtn.setText("Flight Status ");
        statusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBtnActionPerformed(evt);
            }
        });
        jPanel2.add(statusBtn);
        statusBtn.setBounds(80, 220, 460, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 130, 670, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
         AirportCheckInSystem a1 = new AirportCheckInSystem();  
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
 
        FileInputStream fileInputStream1 = null;
        FileInputStream fileInputStream2 = null;
        FileInputStream fileInputStream3 = null;
        FileInputStream fileInputStream4 = null;
        FileOutputStream fileOutputStream = null;
        SequenceInputStream sequenceInputStream = null;

        try
        {
            fileInputStream1 = new FileInputStream("C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\test.csv");
            fileInputStream2 = new FileInputStream("C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\test1.csv");
            fileInputStream3 = new FileInputStream("C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\test2.csv");
            fileInputStream4 = new FileInputStream("C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\test3.csv");
            fileOutputStream = new FileOutputStream("C:\\Users\\Mohd Samir\\Documents\\NetBeansProjects\\AirportCheck-InSystem\\src\\airportcheck\\logFile.csv");

            Vector<FileInputStream> vector = new Vector<FileInputStream>();
            vector.add(fileInputStream1);
            vector.add(fileInputStream2);
            vector.add(fileInputStream3);
            vector.add(fileInputStream4);

            Enumeration<FileInputStream> enumeration = vector.elements();

            sequenceInputStream = new SequenceInputStream(enumeration);
            int i;
            while ((i = sequenceInputStream.read()) != -1)
            {
                fileOutputStream.write(i);
            }
         // JOptionPane.showMessageDialog(this, "SUCCESSFULLY LOADED DATA IN FILE","logFile.csv",JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
        }        finally
        {
            if (fileInputStream1 != null)
            {
                try {
                    fileInputStream1.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (fileInputStream2 != null)
            {
                try {
                    fileInputStream2.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (fileInputStream3 != null)
            {
                try {
                    fileInputStream3.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
              if (fileInputStream4 != null)
            {
                try {
                    fileInputStream3.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
           if (fileOutputStream != null)
            {
                try {
                    fileOutputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (sequenceInputStream != null)
            {
                try {
                    sequenceInputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    LogFile lf = new LogFile();
    lf.setVisible(true);
    this.dispose();
 
          
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void statusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBtnActionPerformed
        Flight_Status fs = new Flight_Status();
        fs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_statusBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
    MainPage mp2 = new MainPage();
    mp2.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void watingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watingBtnActionPerformed
        Waiting_Queue wq = new Waiting_Queue();
        wq.setVisible(true);
     this.dispose();
                
    }//GEN-LAST:event_watingBtnActionPerformed

    private void CheckBtnDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBtnDeskActionPerformed
        Check_In_Desk cid= new Check_In_Desk();
        cid.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_CheckBtnDeskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckBtnDesk;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton statusBtn;
    private javax.swing.JButton watingBtn;
    // End of variables declaration//GEN-END:variables
}
